name: Build and Push Docker Image

# Déclenche le workflow à chaque push sur la branche main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.arianedohou}}
          password: ${{secrets.dckr_pat_OK_2va7_iH679T-2-SaDKxtDZDs}}

      # 3️⃣ Build de l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.arianedohou }}/projet_yolo:latest .

      # 4️⃣ Pousser l'image sur Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.arianedohou }}/projet_yolo:latest
